workflows:
  android-workflow:
    name: Android Build
    instance_type: mac_mini_m1
    environment:
      flutter: 2.10.5  # Older version, more compatible with 2022 codebase
      java: 11
      xcode: latest
    cache:
      cache_paths:
        - ~/.gradle/caches
        - ~/.pub-cache
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Disable analytics
        script: |
          flutter config --no-analytics
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Clear build directory
        script: |
          flutter clean
      - name: Build debug APK
        script: |
          cd "$CM_BUILD_DIR" && flutter build apk --debug
      - name: Display build results
        script: |
          ls -la build/app/outputs/flutter-apk/ || true
    artifacts:
      - build/app/outputs/flutter-apk/*.apk