workflows:
  android-workflow:
    name: Android Build
    instance_type: mac_mini_m1
    environment:
      flutter: 3.3.0
      java: 11
      xcode: latest
    cache:
      cache_paths:
        - ~/.gradle/caches
        - ~/.pub-cache
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Create placeholder Firebase config
        script: |
          echo '{"project_info":{"project_number":"000000000000","project_id":"placeholder-id"}}' > "$CM_BUILD_DIR/android/app/google-services.json"
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Build debug APK
        script: |
          cd "$CM_BUILD_DIR" && flutter build apk --debug --target-platform android-arm64
    artifacts:
      - build/app/outputs/flutter-apk/*.apk